# Generated by Django 5.1.4 on 2025-02-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SDOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemID', models.IntegerField(verbose_name='子项ID')),
                ('ItemName', models.CharField(max_length=20, verbose_name='名称')),
                ('SuperiorID', models.IntegerField(verbose_name='上级项ID')),
                ('SuperiorName', models.CharField(max_length=20, verbose_name='上级项名称')),
                ('LinkPage', models.CharField(max_length=100, verbose_name='链接地址')),
            ],
        ),
    ]
