# Generated by Django 5.1.4 on 2025-02-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdom',
            name='ItemID',
        ),
    ]
