# Generated by Django 5.1.4 on 2025-02-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_remove_sdom_itemid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SDOM',
            new_name='MainPage',
        ),
    ]
